fastlane_version "2.28.3"
default_platform :ios

platform :ios do
  
  # Common

  lane :run_tests do 
    scan(
      scheme: 'CoalescingOperationsReducedBoilerplate-Example',
      skip_build: true
    )
  end
  
end